# Generated by Django 4.2.14 on 2024-08-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CVE",
            fields=[
                # (
                #     "id",
                #     models.BigAutoField(
                #         auto_created=True,
                #         primary_key=True,
                #         serialize=False,
                #         verbose_name="ID",
                #     ),
                # ),
                ("cve_id", models.CharField(max_length=80, unique=True)),
                ("severity", models.CharField(max_length=80)),
                ("last_modified", models.CharField(max_length=80)),
            ],
        ),
    ]
