# Generated by Django 4.2.14 on 2024-08-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CveAttackVec",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("cve_id", models.IntegerField()),
                ("attack_vector", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "attack_vectors",
            },
        ),
        migrations.CreateModel(
            name="CveFact",
            fields=[
                ("cve_id_str", models.CharField(max_length=90, unique=True)),
                (
                    "cve_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "attack_vectors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_api.cveattackvec",
                    ),
                ),
            ],
            options={
                "db_table": "cves_fact",
            },
        ),
        migrations.CreateModel(
            name="CveScores",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("cve_id", models.IntegerField()),
                ("impact_score", models.FloatField()),
                ("exploitability_score", models.FloatField()),
            ],
            options={
                "db_table": "scores",
            },
        ),
        migrations.CreateModel(
            name="CveSeverity",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("cve_id", models.IntegerField()),
                ("severity", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "severity_types",
            },
        ),
        migrations.DeleteModel(
            name="CVE",
        ),
        migrations.AddField(
            model_name="cvefact",
            name="scores",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_api.cvescores"
            ),
        ),
        migrations.AddField(
            model_name="cvefact",
            name="severity_types",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_api.cveseverity"
            ),
        ),
    ]
