# Generated by Django 4.2.14 on 2024-08-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_api", "0002_cveattackvec_cvefact_cvescores_cveseverity_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cveattackvec",
            table="cves_attack_vectors",
        ),
        migrations.AlterModelTable(
            name="cvescores",
            table="cves_scores",
        ),
        migrations.AlterModelTable(
            name="cveseverity",
            table="cves_severity",
        ),
    ]
