# Generated by Django 4.2.14 on 2024-08-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_api",
            "0004_cveattackvec_last_modified_cvescores_last_modified_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvefact",
            old_name="attack_vectors",
            new_name="cves_attack_vectors",
        ),
        migrations.RenameField(
            model_name="cvefact",
            old_name="scores",
            new_name="cves_scores",
        ),
        migrations.RenameField(
            model_name="cvefact",
            old_name="severity_types",
            new_name="cves_severity",
        ),
    ]
