# Generated by Django 4.2.14 on 2024-08-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_api",
            "0005_rename_attack_vectors_cvefact_cves_attack_vectors_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvefact",
            old_name="cves_scores",
            new_name="id",
        ),
    ]
