# Generated by Django 4.2.14 on 2024-08-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_api", "0006_rename_cves_scores_cvefact_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvefact",
            old_name="id",
            new_name="cves_scores",
        ),
    ]
