# Generated by Django 4.2.14 on 2024-08-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_api", "0007_rename_id_cvefact_cves_scores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvefact",
            name="cves_attack_vectors",
        ),
        migrations.RemoveField(
            model_name="cvefact",
            name="cves_scores",
        ),
        migrations.RemoveField(
            model_name="cvefact",
            name="cves_severity",
        ),
    ]
