# Generated by Django 4.2.14 on 2024-08-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_api",
            "0010_alter_cveattackvec_cve_id_alter_cvescores_cve_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cveattackvec",
            name="cve_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_api.cvefact"
            ),
        ),
        migrations.AlterField(
            model_name="cvescores",
            name="cve_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_api.cvefact"
            ),
        ),
        migrations.AlterField(
            model_name="cveseverity",
            name="cve_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_api.cvefact"
            ),
        ),
    ]
